[package]

name = "task_scheduller"
version = "0.0.1"
authors = [ "Diego de Oliveira <diego@diegooliveira.com>" ]

[[bin]]
name = "task_scheduller"

[dependencies]
rand="*"

[dependencies.genetics]
path = "../genetics"